<template>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <div class="chat-container">
      <!-- Chatbot button -->
      <div id="chat-button" class="chat-button" @click="toggleChat">
        <div id="chat-tooltip" class="chat-tooltip">
          Try me! I'm an AI bot generated by DaryXat Team!
          <span class="chat-tooltip-arrow"></span>
        </div>
        <i class="fas fa-comment"></i>
      </div>
  
      <!-- Chat pop-up -->
      <div id="chat-popup" class="chat-popup" :class="{'open': isChatOpen}">
        <div class="chat-header">
          <span class="chat-title">DaryXat chat</span>
          <span class="chat-close" @click="toggleChat">&times;</span>
        </div>
        <div class="chat-content" ref="chatContent">
          <div v-for="(message, index) in messages" :key="index" class="chat-message" :class="{'user-message': isUserMessage(index), 'bot-message': !isUserMessage(index)}">
            <div v-if="isUserMessage(index)" class="message-content user-message-content">
              {{ message }}
            </div>
            <div v-else class="message-content bot-message-content">
              <div class="avatar">
                <img src="../assets/avatar.png" alt="Bot Avatar">
              </div>
              {{ message }}
            </div>
          </div>
        </div>
        <div class="chat-input">
          <div class="input-wrapper">
            <input id="chat-input-field" type="text" placeholder="Type a message..." v-model="inputMessage" @keydown.enter="sendMessage">
            <button id="chat-submit-button" @click="sendMessage">Send</button>
          </div>
        </div>
      </div>
    </div>
  </template>
  
  <script>
  import axios from 'axios';
  
  export default {
    data() {
      return {
        messages: [],
        isChatOpen: false,
        inputMessage: '',
      };
    },
  
    methods: {
      toggleChat() {
        this.isChatOpen = !this.isChatOpen;
  
        if (this.isChatOpen) {
          this.scrollToBottom();
        }
      },
  
      async sendMessage() {
        if (this.inputMessage.trim() === '') {
          return;
        }
  
        const message = this.inputMessage;
        try {
          const response = await axios.post('http://localhost:3000/api/chat/test', { message });
          this.messages.push(message);
          this.messages.push(response.data.response);
  
          // Scroll to the bottom of the chat content after new message is added
          this.scrollToBottom();
        } catch (error) {
          console.error(error);
        }
        
        this.inputMessage = ''; // Clear the input field
      },
  
      isUserMessage(index) {
        return index % 2 === 0;
      },
  
      scrollToBottom() {
        this.$nextTick(() => {
          const chatContentElement = this.$refs.chatContent;
          chatContentElement.scrollTop = chatContentElement.scrollHeight;
        });
      },
    },
  };
  </script>
  
  <style>
    /* Styling for the chatbot button */
.chat-button {
  position: fixed;
  bottom: 20px;
  right: 20px;
  width: 60px; /* Adjust the size as per your preference */
  height: 60px; /* Adjust the size as per your preference */
  background-color: #007bff;
  color: #fff;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 24px;
  cursor: pointer;
  z-index: 1;
}

/* Styling for the chat pop-up */
.chat-popup {
  position: fixed;
  bottom: 20px;
  right: 20px;
  width: 400px;
  max-height: 500px;
  background-color: #fff;
  border: 1px solid #ccc;
  border-radius: 10px;
  overflow: auto; /* Add scroll functionality */
  display: none;
  z-index: 2;
}

.chat-popup.open {
  display: block;
}

/* Styling for chat content */
.chat-content {
  padding: 10px;
}

/* Styling for chat input */
.chat-input {
  padding: 10px;
  border-top: 1px solid #ccc;
  display: flex;
  align-items: center;
  background-color: #fff;
}



.chat-input input {
  flex: 1;
  border: none;
  border-radius: 5px;
  padding: 10px;
  margin-bottom: 10px;
}

.chat-input button {
  margin-left: 10px;
  padding: 10px 20px;
  border: none;
  background: #007bff;
  color: #fff;
  border-radius: 5px;
  cursor: pointer;
}

.chat-message {
  display: flex;
  margin-bottom: 10px;
}

.user-message {
  align-self: flex-end;
  background-color: #007bff;
  color: #fff;
  border-top-right-radius: 10px;
  border-bottom-right-radius: 10px;
}

.bot-message {
  align-self: flex-start;
  background-color: #f1f1f1;
  color: #000;
  border-top-left-radius: 10px;
  border-bottom-left-radius: 10px;
}

.message-content {
  padding: 10px;
}

.bot-message .avatar {
  width: 40px; /* Adjust the size of the avatar as per your preference */
  height: 40px; /* Adjust the size of the avatar as per your preference */
  margin-right: 10px;
}

.bot-message .avatar img {
  width: 100%;
  height: 100%;
  border-radius: 50%;
}



.chat-popup {
  position: fixed;
  bottom: 80px;
  right: 20px;
  width: 400px;
  max-height: 500px;
  background-color: #fff;
  border: 1px solid #ccc;
  border-radius: 10px;
  overflow: auto;
  display: none;
  z-index: 2;
}

.chat-popup.open {
  display: block;
}

.chat-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 10px;
  background-color: #007bff;
  color: #fff;
  border-radius: 10px 10px 0 0;
}

.chat-title {
  font-weight: bold;
}

.chat-close {
  cursor: pointer;
}

.chat-content {
  padding: 10px;
}

.chat-input {
  padding: 10px;
  border-top: 1px solid #ccc;
  display: flex;
  align-items: center;
  background-color: #fff;
}


.chat-tooltip {
  position: absolute;
  bottom: 100%;
  left: 50%;
  transform: translateX(-50%);
  margin-bottom: 20px;
  padding: 15px;
  border-radius: 10px;
  background-color: #007bff;
  color: #fff;
  text-align: center;
  box-shadow: 0px 0px 10px rgba(0,0,0,0.2);
  opacity: 0;
  visibility: hidden;
  transition: opacity 0.3s, visibility 0.3s;
  font-family: 'Montserrat', sans-serif; /* Your desired font goes here */
  font-size: 20px; /* Adjust the size as per your preference */
  font-weight: 700; /* Adjust the weight as per your preference */
}

.chat-button:hover .chat-tooltip {
  opacity: 1;
  visibility: visible;
}

.chat-tooltip-arrow {
  position: absolute;
  top: 100%;
  left: 50%;
  transform: translateX(-50%);
  width: 0;
  height: 0;
  border-left: 10px solid transparent;
  border-right: 10px solid transparent;
  border-top: 10px solid #007bff;
}

  </style>
  